spring.application.name=ai
server.port=${PORT:10000}

# Aiven MySQL Direct Configuration
spring.datasource.url=jdbc:mysql://myprojects-kataripuneethrajiv-688f.b.aivencloud.com:10394/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Khe7k5yB4_5507Eqs44
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Gemini API Key
gemini.api.key=${GKEY:}
